name: Action Workflow

on: [push]

jobs:
    run-github-actions:
        run-on: ubuntu-latest
        steps:
          - name: sample JS action
           uses: actions/hello-world-javascript-action@v1
           with: 
             who-to-greet: devopshint
          - name: Get the output
           run: echo "${{ steps.hello.outout.time }}"
           with: 
             who-to-greet: devopshint